/* Generated by MyraPad at 07.02.2021 16:20:27 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;


namespace temp1.UI
{
	partial class Hud: Grid
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Inventory";
			label1.Margin = new Thickness(0, 0, 7, 0);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			label1.GridRow = 1;

			inventoryImage = new Image();
			inventoryImage.Width = 32;
			inventoryImage.Height = 32;
			inventoryImage.BorderThickness = new Thickness(3);
			inventoryImage.GridColumn = 1;
			inventoryImage.GridRow = 1;
			inventoryImage.Border = new SolidBrush("#FE3930FF");
			inventoryImage.Id = "inventoryImage";

			
			ShowGridLines = false;
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 32,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 16,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 16,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 32,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Widgets.Add(label1);
			Widgets.Add(inventoryImage);
		}

		
		public Image inventoryImage;
	}
}
