/* Generated by MyraPad at 07.02.2021 16:20:27 */
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Myra.Graphics2D.TextureAtlases;

namespace temp1.UI
{
    partial class Hud
    {
        public Hud(ContentManager content, HudService hud)
        {
            BuildUI();
            var inventoryTexture = content.Load<Texture2D>("images/dragons_blade");
            var inventoryRect = new Rectangle(96, 64, 32, 32);
            inventoryImage.Renderable = new TextureRegion(inventoryTexture, inventoryRect);
            inventoryImage.TouchUp += (s, e) => hud.OpenInventory1();
            inventoryImage.MouseEntered += (s,e) => {
                inventoryImage.Width += 4;
                inventoryImage.Height += 4;
            };
            inventoryImage.MouseLeft += (s,e) => {
                inventoryImage.Width -= 4;
                inventoryImage.Height -= 4;
            };
            hud.SetCallbacks(inventoryImage);
        }
    }
}