/* Generated by MyraPad at 08.02.2021 18:29:06 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace temp1.UI
{
	partial class Hud: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Inventory";
			label1.Margin = new Thickness(0, 0, 7, 0);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			label1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			inventoryImage = new Image();
			inventoryImage.Width = 32;
			inventoryImage.Height = 32;
			inventoryImage.Id = "inventoryImage";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Top;
			horizontalStackPanel1.Margin = new Thickness(10);
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(inventoryImage);

			var label2 = new Label();
			label2.Text = "To battle";
			label2.Margin = new Thickness(0, 0, 7, 0);
			label2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;

			battleImage = new Image();
			battleImage.Width = 32;
			battleImage.Height = 32;
			battleImage.Id = "battleImage";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			horizontalStackPanel2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			horizontalStackPanel2.Margin = new Thickness(10);
			horizontalStackPanel2.Widgets.Add(label2);
			horizontalStackPanel2.Widgets.Add(battleImage);

			
			Widgets.Add(horizontalStackPanel1);
			Widgets.Add(horizontalStackPanel2);
		}

		
		public Image inventoryImage;
		public Image battleImage;
	}
}
