/* Generated by MyraPad at 05.02.2021 15:26:51 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using FontStashSharp;

namespace temp1.UI
{
	partial class Inventory1: Grid
	{
		private void BuildUI()
		{
			var textBox1 = new TextBox();
			textBox1.Text = "Player";
			textBox1.Font = MyraEnvironment.DefaultAssetManager.Load<SpriteFontBase>("Content/fonts/commodore-64.fnt");
			textBox1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox1.GridColumn = 1;
			textBox1.GridRow = 1;
			textBox1.GridColumnSpan = 2;
			textBox1.Background = new SolidBrush("#00000000");

			firstPanel = new VerticalStackPanel();
			firstPanel.Background = new SolidBrush("#80562962");
			firstPanel.Id = "firstPanel";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.GridColumn = 1;
			scrollViewer1.GridRow = 2;
			scrollViewer1.Content = firstPanel;

			playerImage = new Image();
			playerImage.MinWidth = 80;
			playerImage.MinHeight = 100;
			playerImage.Margin = new Thickness(0, 22, 0, 10);
			playerImage.BorderThickness = new Thickness(2);
			playerImage.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			playerImage.Border = new SolidBrush("#000000FF");
			playerImage.Id = "playerImage";

			var textBox2 = new TextBox();
			textBox2.Text = "Mighty hero";
			textBox2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox2.Background = new SolidBrush("#00000000");

			var textBox3 = new TextBox();
			textBox3.Text = "Level: 1";
			textBox3.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			textBox3.Background = new SolidBrush("#00000000");

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.GridColumn = 2;
			verticalStackPanel1.GridRow = 2;
			verticalStackPanel1.Background = new SolidBrush("#095744FF");
			verticalStackPanel1.Widgets.Add(playerImage);
			verticalStackPanel1.Widgets.Add(textBox2);
			verticalStackPanel1.Widgets.Add(textBox3);

			closeButton = new TextButton();
			closeButton.Text = "X";
			closeButton.PressedBackground = new SolidBrush("#CC3112FF");
			closeButton.Margin = new Thickness(12, 0, 0, 0);
			closeButton.Padding = new Thickness(10, 2);
			closeButton.GridColumn = 3;
			closeButton.GridRow = 1;
			closeButton.Background = new SolidBrush("#B22922FF");
			closeButton.OverBackground = new SolidBrush("#FE3930FF");
			closeButton.Id = "closeButton";

			
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 225,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 200,
			});
			ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 30,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 350,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Widgets.Add(textBox1);
			Widgets.Add(scrollViewer1);
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(closeButton);
		}

		
		public VerticalStackPanel firstPanel;
		public Image playerImage;
		public TextButton closeButton;
	}
}
