/* Generated by MyraPad at 04.02.2021 15:23:54 */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace temp1.UI
{
	partial class MainMenu: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "My Awesome Game";
			label1.TextColor = Color.Violet;
			label1.Padding = new Thickness(0, 25, 0, 0);
			label1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;

			_menuStartNewGame = new ImageTextButton();
			_menuStartNewGame.Text = "Start New Game";
			_menuStartNewGame.PressedBackground = new SolidBrush("#8C8C8CFF");
			_menuStartNewGame.Margin = new Thickness(0, 0, 0, 6);
			_menuStartNewGame.Padding = new Thickness(14, 4);
			_menuStartNewGame.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_menuStartNewGame.Id = "_menuStartNewGame";

			_menuOptions = new ImageTextButton();
			_menuOptions.Text = "Options";
			_menuOptions.PressedBackground = new SolidBrush("#8C8C8CFF");
			_menuOptions.Margin = new Thickness(0, 0, 0, 6);
			_menuOptions.Padding = new Thickness(14, 4);
			_menuOptions.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_menuOptions.Id = "_menuOptions";

			_menuQuit = new ImageTextButton();
			_menuQuit.Text = "Quit";
			_menuQuit.PressedBackground = new SolidBrush("#8C8C8CFF");
			_menuQuit.Padding = new Thickness(14, 4);
			_menuQuit.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			_menuQuit.Id = "_menuQuit";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalStackPanel1.Widgets.Add(_menuStartNewGame);
			verticalStackPanel1.Widgets.Add(_menuOptions);
			verticalStackPanel1.Widgets.Add(_menuQuit);

			
			Widgets.Add(label1);
			Widgets.Add(verticalStackPanel1);
		}

		
		public ImageTextButton _menuStartNewGame;
		public ImageTextButton _menuOptions;
		public ImageTextButton _menuQuit;
	}
}
